keycloak:
  realm: 'QPExpress'
  auth-server-url: 'https://qpexpress.kz/auth'
  admin-username: 'admin'
  admin-password: 'passwd'
kaspi:
  organization-bin: '230840030304'
  device-token: 'd87e6939-0a82-4f9b-8561-3473ead74ed1'
jetpay:
  project-id: 134112
  secret-key: '496d008778131723a0cc03d6b61bf848daf3d18c963c8478a95c0bcea059d198b9f69a6c4ad6e5e51785337a7dd3456aba75e178308610e92ec416c95451bc05'
spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: my-scheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            dataSource: myDS
            tablePrefix: QRTZ_
          dataSource:
            myDS:
              driver: org.postgresql.Driver
              URL: jdbc:postgresql://qpexpress.kz:5432/qpexpress?currentSchema=quartz
              user: qpexpress-admin
              password: passwd
              maxConnections: 5